// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NS.Infra.Data.AppData;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NS.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251113013859_CreateTableNotaTrilha")]
    partial class CreateTableNotaTrilha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NS.Domain.Entities.NotaTrilhaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NOTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdTrilha")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TRILHA");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar2(400)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<int>("ValorNota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VALOR_NOTA");

                    b.HasKey("Id");

                    b.HasIndex("IdTrilha");

                    b.ToTable("NS_NOTA_TRILHA");
                });

            modelBuilder.Entity("NS.Domain.Entities.TrilhaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TRILHA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("AREA");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar2(400)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("NIVEL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("NS_TRILHA");
                });

            modelBuilder.Entity("NS.Domain.Entities.NotaTrilhaEntity", b =>
                {
                    b.HasOne("NS.Domain.Entities.TrilhaEntity", "Trilha")
                        .WithMany("Notas")
                        .HasForeignKey("IdTrilha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("NS.Domain.Entities.TrilhaEntity", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
